spring:
    
	profiles:
        
		active:
        
		-dev
        


---


spring:

    	profiles: dev    #开发环境
    
	application:
        
		name:microservicecloud-config-kmkj-dev
        

---


spring:

    	profiles: test   #测试环境
    
	application:
        
		name: microservicecloud-config-kmkj-dev
 
 
#保存为UTF-8格式




























