spring:
    
  profiles:
        
    active:
        
      - dev
        


---

server:
  port: 8001

spring:

  profiles: dev    
  application:
        
    name: microservicecloud-config-dept-client 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  
    driver-class-name: org.gjt.mm.mysql.Driver   
    url: jdbc:mysql://localhost:3306/kmkj_db    
    username: root
    password: 123456
    dbcp2:
      min-idle: 5     
      initial-size: 5 
      max-total: 5  
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所有路径
  type-aliases-package: com.kmkj.springcloud.pojo  #所有POJO别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml    #mapper映射文件


eureka:
  client: #客户端注册进Eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: dept-8001.com    #替换默认的微服务名字
    prefer-ip-address: true   #访问路径可以显示IP

info:  #修改info信息(当点击服务注册的名字后)
  app.name: kmkj-microservicecloud-springcloudconfig01
  company.name: www.kmkj.com
  build.artifactId: ${project.artifactId}  #Eureka注册服务的info动态显示artifactId和version
  build.version: ${project.version}

---

server:
  port: 8001

spring:

  profiles: test
  application:
        
    name: microservicecloud-config-dept-client 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  
    driver-class-name: org.gjt.mm.mysql.Driver   
    url: jdbc:mysql://localhost:3306/kmkj_db    
    username: root
    password: 123456
    dbcp2:
      min-idle: 5     
      initial-size: 5 
      max-total: 5  
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所有路径
  type-aliases-package: com.kmkj.springcloud.pojo  #所有POJO别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml    #mapper映射文件


eureka:
  client: #客户端注册进Eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: dept-8001.com    #替换默认的微服务名字
    prefer-ip-address: true   #访问路径可以显示IP

info:  #修改info信息(当点击服务注册的名字后)
  app.name: kmkj-microservicecloud-springcloudconfig02
  company.name: www.kmkj.com
  build.artifactId: ${project.artifactId}  #Eureka注册服务的info动态显示artifactId和version
  build.version: ${project.version}





































